### ISSUE TITLE
一个关于Chopsticks 小问题

### ISSUE THREAD

**Issue by hqwangningbo** [AcalaNetwork/e2e-tests#66]
想问下@xlc大佬，Chopsticks是不是只适合测试线上环境，有这样的一个场景，比如上线前测试我需要测试功能，也想用线上的链状态，这样的场景是不是Chopsticks不适用，只能等他升级升上去，才能用Chopsticks做测试?

**Comment by zjb0807** [comment]
You can use the new runtime with an on-chain state
https://github.com/AcalaNetwork/chopsticks/blob/master/configs/karura.yml#L5

Or upgrade the runtime with `setCode`

**Comment by hqwangningbo** [comment]
感谢🙏
